#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronicApp
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[System.Data.Linq.Mapping.DatabaseAttribute(Name="ElectronicApp_Security")]
	public partial class ElectronicAppSecurityDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public ElectronicAppSecurityDBDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["ElectronicApp_SecurityConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ElectronicAppSecurityDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ElectronicAppSecurityDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ElectronicAppSecurityDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ElectronicAppSecurityDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[Function(Name="dbo.uspLoginWebuser")]
		public ISingleResult<uspLoginWebuserResult> uspLoginWebuser([Parameter(Name="UserName", DbType="VarChar(50)")] string userName, [Parameter(Name="Password", DbType="VarChar(50)")] string password)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userName, password);
			return ((ISingleResult<uspLoginWebuserResult>)(result.ReturnValue));
		}
		
		[Function(Name="dbo.uspInsertAttachmentData")]
		public int uspInsertAttachmentData([Parameter(Name="ObjectID", DbType="UniqueIdentifier")] System.Nullable<System.Guid> objectID, [Parameter(Name="OwnerID", DbType="UniqueIdentifier")] System.Nullable<System.Guid> ownerID, [Parameter(Name="Phrase", DbType="Image")] System.Data.Linq.Binary phrase, [Parameter(Name="Vector", DbType="Image")] System.Data.Linq.Binary vector)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), objectID, ownerID, phrase, vector);
			return ((int)(result.ReturnValue));
		}
		
		[Function(Name="dbo.uspLoginBrokeruser")]
		public ISingleResult<uspLoginBrokeruserResult> uspLoginBrokeruser([Parameter(DbType="VarChar(50)")] string login, [Parameter(DbType="VarChar(200)")] string password)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), login, password);
			return ((ISingleResult<uspLoginBrokeruserResult>)(result.ReturnValue));
		}
		
		[Function(Name="dbo.uspCheckUsername")]
		public ISingleResult<uspCheckUsernameResult> uspCheckUsername([Parameter(Name="User", DbType="VarChar(50)")] string user)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), user);
			return ((ISingleResult<uspCheckUsernameResult>)(result.ReturnValue));
		}
		
		[Function(Name="dbo.uspInsertWebUser")]
		public int uspInsertWebUser([Parameter(Name="UserID", DbType="UniqueIdentifier")] System.Nullable<System.Guid> userID, [Parameter(Name="OwnerID", DbType="UniqueIdentifier")] System.Nullable<System.Guid> ownerID, [Parameter(Name="Username", DbType="Text")] string username, [Parameter(Name="Password", DbType="Text")] string password)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userID, ownerID, username, password);
			return ((int)(result.ReturnValue));
		}
	}
	
	public partial class uspLoginWebuserResult
	{
		
		private System.Guid _AssociatedWith;
		
		public uspLoginWebuserResult()
		{
		}
		
		[Column(Storage="_AssociatedWith", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid AssociatedWith
		{
			get
			{
				return this._AssociatedWith;
			}
			set
			{
				if ((this._AssociatedWith != value))
				{
					this._AssociatedWith = value;
				}
			}
		}
	}
	
	public partial class uspLoginBrokeruserResult
	{
		
		private System.Guid _associatedWith;
		
		public uspLoginBrokeruserResult()
		{
		}
		
		[Column(Storage="_associatedWith", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid associatedWith
		{
			get
			{
				return this._associatedWith;
			}
			set
			{
				if ((this._associatedWith != value))
				{
					this._associatedWith = value;
				}
			}
		}
	}
	
	public partial class uspCheckUsernameResult
	{
		
		private System.Guid _UserID;
		
		public uspCheckUsernameResult()
		{
		}
		
		[Column(Storage="_UserID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this._UserID = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
