<?xml version="1.0" encoding="utf-8"?><Database Name="ElectronicApp_Security" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=SERVER2\MSSQLSERVER2005,4889;Initial Catalog=ElectronicApp_Security;User ID=WebUser" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="ElectronicApp_SecurityConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.uspAlterWebUser" Method="uspAlterWebUser">
    <Parameter Name="UserID" Parameter="userID" Type="System.Guid" DbType="UniqueIdentifier" />
    <Parameter Name="Username" Parameter="username" Type="System.String" DbType="Text" />
    <Parameter Name="Password" Parameter="password" Type="System.String" DbType="Text" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.uspAlterBrokerUser" Method="uspAlterBrokerUser">
    <Parameter Name="UserID" Parameter="userID" Type="System.Guid" DbType="UniqueIdentifier" />
    <Parameter Name="Username" Parameter="username" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Password" Parameter="password" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.uspLoginWebuser" Method="uspLoginWebuser">
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Password" Parameter="password" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="uspLoginWebuserResult">
      <Column Name="AssociatedWith" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.uspCheckUsername" Method="uspCheckUsername">
    <Parameter Name="User" Parameter="user" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="uspCheckUsernameResult">
      <Column Name="UserID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.uspGetBrokerUserByOwnerID" Method="uspGetBrokerUserByOwnerID">
    <Parameter Name="OwnerID" Parameter="ownerID" Type="System.Guid" DbType="UniqueIdentifier" />
    <ElementType Name="uspGetBrokerUserByOwnerIDResult">
      <Column Name="UserID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="AssociatedWith" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="AddedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.uspGetWebUserByOwnerID" Method="uspGetWebUserByOwnerID">
    <Parameter Name="OwnerID" Parameter="ownerID" Type="System.Guid" DbType="UniqueIdentifier" />
    <ElementType Name="uspGetWebUserByOwnerIDResult">
      <Column Name="UserID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="AssociatedWith" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="AddedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ValidFrom" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ValidTo" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.uspInsertAttachmentData" Method="uspInsertAttachmentData">
    <Parameter Name="ObjectID" Parameter="objectID" Type="System.Guid" DbType="UniqueIdentifier" />
    <Parameter Name="OwnerID" Parameter="ownerID" Type="System.Guid" DbType="UniqueIdentifier" />
    <Parameter Name="Phrase" Parameter="phrase" Type="System.Data.Linq.Binary" DbType="Image" />
    <Parameter Name="Vector" Parameter="vector" Type="System.Data.Linq.Binary" DbType="Image" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.uspInsertWebUser" Method="uspInsertWebUser">
    <Parameter Name="UserID" Parameter="userID" Type="System.Guid" DbType="UniqueIdentifier" />
    <Parameter Name="OwnerID" Parameter="ownerID" Type="System.Guid" DbType="UniqueIdentifier" />
    <Parameter Name="Username" Parameter="username" Type="System.String" DbType="Text" />
    <Parameter Name="Password" Parameter="password" Type="System.String" DbType="Text" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.uspLogAudit" Method="uspLogAudit">
    <Parameter Name="EntryID" Parameter="entryID" Type="System.Guid" DbType="UniqueIdentifier" />
    <Parameter Name="EventStatus" Parameter="eventStatus" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="EventDescription" Parameter="eventDescription" Type="System.String" DbType="VarChar(500)" />
    <Parameter Name="EventTriggeredBy" Parameter="eventTriggeredBy" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="EventType" Parameter="eventType" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.uspLoginBrokeruser" Method="uspLoginBrokeruser">
    <Parameter Name="login" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="password" Type="System.String" DbType="VarChar(200)" />
    <ElementType Name="uspLoginBrokeruserResult">
      <Column Name="associatedWith" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>