#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronicApp
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ElectronipApp")]
	public partial class ElectronicAppDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public ElectronicAppDBDataContext() : 
				base(System.Configuration.ConfigurationManager.ConnectionStrings["ElectronipAppConnectionString1"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ElectronicAppDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ElectronicAppDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ElectronicAppDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ElectronicAppDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspGetClientCoverageOptions")]
		public ISingleResult<uspGetClientCoverageOptionsResult> uspGetClientCoverageOptions([global::System.Data.Linq.Mapping.ParameterAttribute(Name="OwnerID", DbType="UniqueIdentifier")] System.Nullable<System.Guid> ownerID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), ownerID);
			return ((ISingleResult<uspGetClientCoverageOptionsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspGetBrokerByID")]
		public ISingleResult<uspGetBrokerByIDResult> uspGetBrokerByID([global::System.Data.Linq.Mapping.ParameterAttribute(Name="BrokerID", DbType="UniqueIdentifier")] System.Nullable<System.Guid> brokerID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), brokerID);
			return ((ISingleResult<uspGetBrokerByIDResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspGetClientPlanOptions")]
		public ISingleResult<uspGetClientPlanOptionsResult> uspGetClientPlanOptions([global::System.Data.Linq.Mapping.ParameterAttribute(Name="OwnerID", DbType="UniqueIdentifier")] System.Nullable<System.Guid> ownerID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), ownerID);
			return ((ISingleResult<uspGetClientPlanOptionsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspGetBrokerContact")]
		public ISingleResult<uspGetBrokerContactResult> uspGetBrokerContact([global::System.Data.Linq.Mapping.ParameterAttribute(Name="OwnerID", DbType="UniqueIdentifier")] System.Nullable<System.Guid> ownerID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), ownerID);
			return ((ISingleResult<uspGetBrokerContactResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspUpdateEnrolleeCompletionStatus")]
		public int uspUpdateEnrolleeCompletionStatus([global::System.Data.Linq.Mapping.ParameterAttribute(Name="EnrolleeID", DbType="UniqueIdentifier")] System.Nullable<System.Guid> enrolleeID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> status)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), enrolleeID, status);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspDoesEnrolleeExist")]
		public ISingleResult<uspDoesEnrolleeExistResult> uspDoesEnrolleeExist([global::System.Data.Linq.Mapping.ParameterAttribute(Name="OwnerID", DbType="UniqueIdentifier")] System.Nullable<System.Guid> ownerID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FirstName", DbType="VarChar(100)")] string firstName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LastName", DbType="VarChar(100)")] string lastName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BirthDate", DbType="VarChar(50)")] string birthDate)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), ownerID, firstName, lastName, birthDate);
			return ((ISingleResult<uspDoesEnrolleeExistResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspInsertEnrollee")]
		public int uspInsertEnrollee([global::System.Data.Linq.Mapping.ParameterAttribute(Name="EnrolleeID", DbType="UniqueIdentifier")] System.Nullable<System.Guid> enrolleeID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="OwnerID", DbType="UniqueIdentifier")] System.Nullable<System.Guid> ownerID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FirstName", DbType="VarChar(100)")] string firstName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LastName", DbType="VarChar(100)")] string lastName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BirthDate", DbType="VarChar(50)")] string birthDate, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> isComplete, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AddedBy", DbType="VarChar(100)")] string addedBy)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), enrolleeID, ownerID, firstName, lastName, birthDate, isComplete, addedBy);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspGetClientContact")]
		public ISingleResult<uspGetClientContactResult> uspGetClientContact([global::System.Data.Linq.Mapping.ParameterAttribute(Name="OwnerID", DbType="UniqueIdentifier")] System.Nullable<System.Guid> ownerID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), ownerID);
			return ((ISingleResult<uspGetClientContactResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspInsertSubmission")]
		public int uspInsertSubmission([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SubmissionID", DbType="UniqueIdentifier")] System.Nullable<System.Guid> submissionID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="OwnerID", DbType="UniqueIdentifier")] System.Nullable<System.Guid> ownerID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FileName", DbType="VarChar(100)")] string fileName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Extension", DbType="VarChar(10)")] string extension, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AddedBy", DbType="VarChar(100)")] string addedBy)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), submissionID, ownerID, fileName, extension, addedBy);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspGetClientCarriers")]
		public ISingleResult<uspGetClientCarriersResult> uspGetClientCarriers([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ClientID", DbType="UniqueIdentifier")] System.Nullable<System.Guid> clientID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), clientID);
			return ((ISingleResult<uspGetClientCarriersResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspGetClientListByOwnerID")]
		public ISingleResult<uspGetClientListByOwnerIDResult> uspGetClientListByOwnerID([global::System.Data.Linq.Mapping.ParameterAttribute(Name="OwnerID", DbType="UniqueIdentifier")] System.Nullable<System.Guid> ownerID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), ownerID);
			return ((ISingleResult<uspGetClientListByOwnerIDResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspGetSubmissionsByClientID")]
		public ISingleResult<uspGetSubmissionsByClientIDResult> uspGetSubmissionsByClientID([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="UniqueIdentifier")] System.Nullable<System.Guid> ownerid)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), ownerid);
			return ((ISingleResult<uspGetSubmissionsByClientIDResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspAlterBrokerInfo")]
		public int uspAlterBrokerInfo([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="UniqueIdentifier")] System.Nullable<System.Guid> brokerid, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string firstname, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string lastname, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(15)")] string phone, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(15)")] string faxnum, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string address, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string city, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(2)")] string state, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(5)")] string zip)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), brokerid, firstname, lastname, email, phone, faxnum, address, city, state, zip);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspGetEnrolleeByID")]
		public ISingleResult<uspGetEnrolleeByIDResult> uspGetEnrolleeByID([global::System.Data.Linq.Mapping.ParameterAttribute(Name="EnrolleeID", DbType="UniqueIdentifier")] System.Nullable<System.Guid> enrolleeID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), enrolleeID);
			return ((ISingleResult<uspGetEnrolleeByIDResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspInsertClient")]
		public int uspInsertClient([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ClientID", DbType="UniqueIdentifier")] System.Nullable<System.Guid> clientID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="OwnerID", DbType="UniqueIdentifier")] System.Nullable<System.Guid> ownerID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EmployerName", DbType="VarChar(100)")] string employerName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TaxID", DbType="VarChar(100)")] string taxID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), clientID, ownerID, employerName, taxID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspInsertClientOptions")]
		public int uspInsertClientOptions([global::System.Data.Linq.Mapping.ParameterAttribute(Name="OptionsID", DbType="UniqueIdentifier")] System.Nullable<System.Guid> optionsID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="OwnerID", DbType="UniqueIdentifier")] System.Nullable<System.Guid> ownerID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> med, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> den, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> lif, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> vis, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> dis)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), optionsID, ownerID, med, den, lif, vis, dis);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspInsertClientCarrier")]
		public int uspInsertClientCarrier([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CID", DbType="UniqueIdentifier")] System.Nullable<System.Guid> cID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Client", DbType="UniqueIdentifier")] System.Nullable<System.Guid> client, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Carrier", DbType="VarChar(100)")] string carrier)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cID, client, carrier);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspInsertClientInfo")]
		public int uspInsertClientInfo([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="UniqueIdentifier")] System.Nullable<System.Guid> contactID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="UniqueIdentifier")] System.Nullable<System.Guid> ownerID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Text")] string phone, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Text")] string fax, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Text")] string address, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Text")] string city, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Text")] string state, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Text")] string zip)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), contactID, ownerID, phone, fax, address, city, state, zip);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspAlterClientInfo")]
		public int uspAlterClientInfo([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ClientID", DbType="UniqueIdentifier")] System.Nullable<System.Guid> clientID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Text")] string employer, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Text")] string taxid, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Text")] string phone, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Text")] string fax, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Text")] string address, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Text")] string city, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Text")] string state, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Text")] string zip)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), clientID, employer, taxid, phone, fax, address, city, state, zip);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspGetClientByID")]
		public ISingleResult<uspGetClientByIDResult> uspGetClientByID([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="UniqueIdentifier")] System.Nullable<System.Guid> clientID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), clientID);
			return ((ISingleResult<uspGetClientByIDResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspGetCarrierOptions")]
		public ISingleResult<uspGetCarrierOptionsResult> uspGetCarrierOptions()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<uspGetCarrierOptionsResult>)(result.ReturnValue));
		}
	}
	
	public partial class uspGetClientCoverageOptionsResult
	{
		
		private System.Guid _OptionsID;
		
		private System.Guid _OwnerID;
		
		private bool _Medical;
		
		private bool _Dental;
		
		private bool _Life;
		
		private bool _Vision;
		
		private bool _Disability;
		
		public uspGetClientCoverageOptionsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OptionsID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid OptionsID
		{
			get
			{
				return this._OptionsID;
			}
			set
			{
				if ((this._OptionsID != value))
				{
					this._OptionsID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OwnerID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid OwnerID
		{
			get
			{
				return this._OwnerID;
			}
			set
			{
				if ((this._OwnerID != value))
				{
					this._OwnerID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Medical", DbType="Bit NOT NULL")]
		public bool Medical
		{
			get
			{
				return this._Medical;
			}
			set
			{
				if ((this._Medical != value))
				{
					this._Medical = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dental", DbType="Bit NOT NULL")]
		public bool Dental
		{
			get
			{
				return this._Dental;
			}
			set
			{
				if ((this._Dental != value))
				{
					this._Dental = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Life", DbType="Bit NOT NULL")]
		public bool Life
		{
			get
			{
				return this._Life;
			}
			set
			{
				if ((this._Life != value))
				{
					this._Life = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vision", DbType="Bit NOT NULL")]
		public bool Vision
		{
			get
			{
				return this._Vision;
			}
			set
			{
				if ((this._Vision != value))
				{
					this._Vision = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Disability", DbType="Bit NOT NULL")]
		public bool Disability
		{
			get
			{
				return this._Disability;
			}
			set
			{
				if ((this._Disability != value))
				{
					this._Disability = value;
				}
			}
		}
	}
	
	public partial class uspGetBrokerByIDResult
	{
		
		private System.Guid _BrokerID;
		
		private string _FirstName;
		
		private string _LastName;
		
		public uspGetBrokerByIDResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BrokerID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid BrokerID
		{
			get
			{
				return this._BrokerID;
			}
			set
			{
				if ((this._BrokerID != value))
				{
					this._BrokerID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this._FirstName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this._LastName = value;
				}
			}
		}
	}
	
	public partial class uspGetClientPlanOptionsResult
	{
		
		private System.Guid _ClientPlanOptionID;
		
		private System.Guid _OwnerID;
		
		private string _PlanName;
		
		public uspGetClientPlanOptionsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClientPlanOptionID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid ClientPlanOptionID
		{
			get
			{
				return this._ClientPlanOptionID;
			}
			set
			{
				if ((this._ClientPlanOptionID != value))
				{
					this._ClientPlanOptionID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OwnerID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid OwnerID
		{
			get
			{
				return this._OwnerID;
			}
			set
			{
				if ((this._OwnerID != value))
				{
					this._OwnerID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PlanName", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string PlanName
		{
			get
			{
				return this._PlanName;
			}
			set
			{
				if ((this._PlanName != value))
				{
					this._PlanName = value;
				}
			}
		}
	}
	
	public partial class uspGetBrokerContactResult
	{
		
		private System.Guid _ContactID;
		
		private System.Guid _OwnerID;
		
		private string _Address;
		
		private string _City;
		
		private string _State;
		
		private string _Zip;
		
		private string _PhoneNumber;
		
		private string _Fax;
		
		private string _Email;
		
		public uspGetBrokerContactResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid ContactID
		{
			get
			{
				return this._ContactID;
			}
			set
			{
				if ((this._ContactID != value))
				{
					this._ContactID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OwnerID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid OwnerID
		{
			get
			{
				return this._OwnerID;
			}
			set
			{
				if ((this._OwnerID != value))
				{
					this._OwnerID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this._Address = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this._City = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State", DbType="VarChar(2) NOT NULL", CanBeNull=false)]
		public string State
		{
			get
			{
				return this._State;
			}
			set
			{
				if ((this._State != value))
				{
					this._State = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zip", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string Zip
		{
			get
			{
				return this._Zip;
			}
			set
			{
				if ((this._Zip != value))
				{
					this._Zip = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhoneNumber", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string PhoneNumber
		{
			get
			{
				return this._PhoneNumber;
			}
			set
			{
				if ((this._PhoneNumber != value))
				{
					this._PhoneNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fax", DbType="VarChar(10)")]
		public string Fax
		{
			get
			{
				return this._Fax;
			}
			set
			{
				if ((this._Fax != value))
				{
					this._Fax = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
	}
	
	public partial class uspDoesEnrolleeExistResult
	{
		
		private System.Guid _EnrolleeID;
		
		public uspDoesEnrolleeExistResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EnrolleeID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid EnrolleeID
		{
			get
			{
				return this._EnrolleeID;
			}
			set
			{
				if ((this._EnrolleeID != value))
				{
					this._EnrolleeID = value;
				}
			}
		}
	}
	
	public partial class uspGetClientContactResult
	{
		
		private System.Guid _ContactID;
		
		private System.Guid _OwnerID;
		
		private string _Phone;
		
		private string _Fax;
		
		private string _Address;
		
		private string _City;
		
		private string _state;
		
		private string _zip;
		
		public uspGetClientContactResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid ContactID
		{
			get
			{
				return this._ContactID;
			}
			set
			{
				if ((this._ContactID != value))
				{
					this._ContactID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OwnerID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid OwnerID
		{
			get
			{
				return this._OwnerID;
			}
			set
			{
				if ((this._OwnerID != value))
				{
					this._OwnerID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Phone
		{
			get
			{
				return this._Phone;
			}
			set
			{
				if ((this._Phone != value))
				{
					this._Phone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fax", DbType="VarChar(50)")]
		public string Fax
		{
			get
			{
				return this._Fax;
			}
			set
			{
				if ((this._Fax != value))
				{
					this._Fax = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this._Address = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this._City = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_state", DbType="VarChar(2) NOT NULL", CanBeNull=false)]
		public string state
		{
			get
			{
				return this._state;
			}
			set
			{
				if ((this._state != value))
				{
					this._state = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_zip", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string zip
		{
			get
			{
				return this._zip;
			}
			set
			{
				if ((this._zip != value))
				{
					this._zip = value;
				}
			}
		}
	}
	
	public partial class uspGetClientCarriersResult
	{
		
		private string _carrierName;
		
		private System.Guid _carrierID;
		
		public uspGetClientCarriersResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_carrierName", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string carrierName
		{
			get
			{
				return this._carrierName;
			}
			set
			{
				if ((this._carrierName != value))
				{
					this._carrierName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_carrierID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid carrierID
		{
			get
			{
				return this._carrierID;
			}
			set
			{
				if ((this._carrierID != value))
				{
					this._carrierID = value;
				}
			}
		}
	}
	
	public partial class uspGetClientListByOwnerIDResult
	{
		
		private System.Guid _ClientID;
		
		private System.Guid _OwnerID;
		
		private string _EmployerName;
		
		private string _TaxID;
		
		public uspGetClientListByOwnerIDResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClientID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid ClientID
		{
			get
			{
				return this._ClientID;
			}
			set
			{
				if ((this._ClientID != value))
				{
					this._ClientID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OwnerID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid OwnerID
		{
			get
			{
				return this._OwnerID;
			}
			set
			{
				if ((this._OwnerID != value))
				{
					this._OwnerID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployerName", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string EmployerName
		{
			get
			{
				return this._EmployerName;
			}
			set
			{
				if ((this._EmployerName != value))
				{
					this._EmployerName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaxID", DbType="VarChar(100)")]
		public string TaxID
		{
			get
			{
				return this._TaxID;
			}
			set
			{
				if ((this._TaxID != value))
				{
					this._TaxID = value;
				}
			}
		}
	}
	
	public partial class uspGetSubmissionsByClientIDResult
	{
		
		private System.Guid _SubmissionID;
		
		private System.Guid _OwnerID;
		
		private string _FileName;
		
		private string _Extension;
		
		private string _AddedBy;
		
		private System.DateTime _AddedDate;
		
		public uspGetSubmissionsByClientIDResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubmissionID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid SubmissionID
		{
			get
			{
				return this._SubmissionID;
			}
			set
			{
				if ((this._SubmissionID != value))
				{
					this._SubmissionID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OwnerID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid OwnerID
		{
			get
			{
				return this._OwnerID;
			}
			set
			{
				if ((this._OwnerID != value))
				{
					this._OwnerID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileName", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string FileName
		{
			get
			{
				return this._FileName;
			}
			set
			{
				if ((this._FileName != value))
				{
					this._FileName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Extension", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Extension
		{
			get
			{
				return this._Extension;
			}
			set
			{
				if ((this._Extension != value))
				{
					this._Extension = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddedBy", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string AddedBy
		{
			get
			{
				return this._AddedBy;
			}
			set
			{
				if ((this._AddedBy != value))
				{
					this._AddedBy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddedDate", DbType="DateTime NOT NULL")]
		public System.DateTime AddedDate
		{
			get
			{
				return this._AddedDate;
			}
			set
			{
				if ((this._AddedDate != value))
				{
					this._AddedDate = value;
				}
			}
		}
	}
	
	public partial class uspGetEnrolleeByIDResult
	{
		
		private System.Guid _EnrolleeID;
		
		private System.Guid _OwnerID;
		
		private string _FirstName;
		
		private string _LastName;
		
		private string _BirthDate;
		
		private bool _SubmissionComplete;
		
		private string _AddedBy;
		
		private System.DateTime _AddedDate;
		
		public uspGetEnrolleeByIDResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EnrolleeID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid EnrolleeID
		{
			get
			{
				return this._EnrolleeID;
			}
			set
			{
				if ((this._EnrolleeID != value))
				{
					this._EnrolleeID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OwnerID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid OwnerID
		{
			get
			{
				return this._OwnerID;
			}
			set
			{
				if ((this._OwnerID != value))
				{
					this._OwnerID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this._FirstName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this._LastName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BirthDate", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string BirthDate
		{
			get
			{
				return this._BirthDate;
			}
			set
			{
				if ((this._BirthDate != value))
				{
					this._BirthDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubmissionComplete", DbType="Bit NOT NULL")]
		public bool SubmissionComplete
		{
			get
			{
				return this._SubmissionComplete;
			}
			set
			{
				if ((this._SubmissionComplete != value))
				{
					this._SubmissionComplete = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddedBy", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string AddedBy
		{
			get
			{
				return this._AddedBy;
			}
			set
			{
				if ((this._AddedBy != value))
				{
					this._AddedBy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddedDate", DbType="DateTime NOT NULL")]
		public System.DateTime AddedDate
		{
			get
			{
				return this._AddedDate;
			}
			set
			{
				if ((this._AddedDate != value))
				{
					this._AddedDate = value;
				}
			}
		}
	}
	
	public partial class uspGetClientByIDResult
	{
		
		private System.Guid _ClientID;
		
		private System.Guid _OwnerID;
		
		private string _EmployerName;
		
		private string _TaxID;
		
		public uspGetClientByIDResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClientID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid ClientID
		{
			get
			{
				return this._ClientID;
			}
			set
			{
				if ((this._ClientID != value))
				{
					this._ClientID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OwnerID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid OwnerID
		{
			get
			{
				return this._OwnerID;
			}
			set
			{
				if ((this._OwnerID != value))
				{
					this._OwnerID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployerName", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string EmployerName
		{
			get
			{
				return this._EmployerName;
			}
			set
			{
				if ((this._EmployerName != value))
				{
					this._EmployerName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaxID", DbType="VarChar(100)")]
		public string TaxID
		{
			get
			{
				return this._TaxID;
			}
			set
			{
				if ((this._TaxID != value))
				{
					this._TaxID = value;
				}
			}
		}
	}
	
	public partial class uspGetCarrierOptionsResult
	{
		
		private System.Guid _CarrierID;
		
		private string _Name;
		
		public uspGetCarrierOptionsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CarrierID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid CarrierID
		{
			get
			{
				return this._CarrierID;
			}
			set
			{
				if ((this._CarrierID != value))
				{
					this._CarrierID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
