<?xml version="1.0" encoding="utf-8"?><Database Name="ElectronipApp" Class="ElectronicAppDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=SERVER2\MSSQLSERVER2005,4889;Initial Catalog=ElectronipApp;Persist Security Info=True;User ID=WebUser" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="ElectronipAppConnectionString1" Provider="System.Data.SqlClient" />
  <Function Name="dbo.uspAlterBrokerInfo" Method="uspAlterBrokerInfo">
    <Parameter Name="brokerid" Type="System.Guid" DbType="UniqueIdentifier" />
    <Parameter Name="firstname" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="lastname" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="email" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="phone" Type="System.String" DbType="VarChar(15)" />
    <Parameter Name="faxnum" Type="System.String" DbType="VarChar(15)" />
    <Parameter Name="address" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="city" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="state" Type="System.String" DbType="VarChar(2)" />
    <Parameter Name="zip" Type="System.String" DbType="VarChar(5)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.uspInsertSubmission" Method="uspInsertSubmission">
    <Parameter Name="SubmissionID" Parameter="submissionID" Type="System.Guid" DbType="UniqueIdentifier" />
    <Parameter Name="OwnerID" Parameter="ownerID" Type="System.Guid" DbType="UniqueIdentifier" />
    <Parameter Name="FileName" Parameter="fileName" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Extension" Parameter="extension" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="AddedBy" Parameter="addedBy" Type="System.String" DbType="VarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.uspAlterClientInfo" Method="uspAlterClientInfo">
    <Parameter Name="ClientID" Parameter="clientID" Type="System.Guid" DbType="UniqueIdentifier" />
    <Parameter Name="employer" Type="System.String" DbType="Text" />
    <Parameter Name="taxid" Type="System.String" DbType="Text" />
    <Parameter Name="phone" Type="System.String" DbType="Text" />
    <Parameter Name="fax" Type="System.String" DbType="Text" />
    <Parameter Name="address" Type="System.String" DbType="Text" />
    <Parameter Name="city" Type="System.String" DbType="Text" />
    <Parameter Name="state" Type="System.String" DbType="Text" />
    <Parameter Name="zip" Type="System.String" DbType="Text" />
    <Parameter Name="EligableEmployees" Parameter="eligableEmployees" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.uspDoesEnrolleeExist" Method="uspDoesEnrolleeExist">
    <Parameter Name="OwnerID" Parameter="ownerID" Type="System.Guid" DbType="UniqueIdentifier" />
    <Parameter Name="FirstName" Parameter="firstName" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="LastName" Parameter="lastName" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="BirthDate" Parameter="birthDate" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="uspDoesEnrolleeExistResult">
      <Column Name="EnrolleeID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.uspGetBrokerByID" Method="uspGetBrokerByID">
    <Parameter Name="BrokerID" Parameter="brokerID" Type="System.Guid" DbType="UniqueIdentifier" />
    <ElementType Name="uspGetBrokerByIDResult">
      <Column Name="BrokerID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.uspGetBrokerContact" Method="uspGetBrokerContact">
    <Parameter Name="OwnerID" Parameter="ownerID" Type="System.Guid" DbType="UniqueIdentifier" />
    <ElementType Name="uspGetBrokerContactResult">
      <Column Name="ContactID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="OwnerID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="City" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="State" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="Zip" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="PhoneNumber" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="Fax" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.uspGetCarrierOptions" Method="uspGetCarrierOptions">
    <ElementType Name="uspGetCarrierOptionsResult">
      <Column Name="CarrierID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.uspGetClientByID" Method="uspGetClientByID">
    <Parameter Name="clientID" Type="System.Guid" DbType="UniqueIdentifier" />
    <ElementType Name="uspGetClientByIDResult">
      <Column Name="ClientID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="OwnerID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="EmployerName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="TaxID" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.uspGetClientCarriers" Method="uspGetClientCarriers">
    <Parameter Name="ClientID" Parameter="clientID" Type="System.Guid" DbType="UniqueIdentifier" />
    <ElementType Name="uspGetClientCarriersResult">
      <Column Name="carrierName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="carrierID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.uspGetClientContact" Method="uspGetClientContact">
    <Parameter Name="OwnerID" Parameter="ownerID" Type="System.Guid" DbType="UniqueIdentifier" />
    <ElementType Name="uspGetClientContactResult">
      <Column Name="ContactID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="OwnerID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Phone" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Fax" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="City" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="state" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="zip" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.uspGetClientCoverageOptions" Method="uspGetClientCoverageOptions">
    <Parameter Name="OwnerID" Parameter="ownerID" Type="System.Guid" DbType="UniqueIdentifier" />
    <ElementType Name="uspGetClientCoverageOptionsResult">
      <Column Name="OptionsID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="OwnerID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Medical" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Dental" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Life" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Vision" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Disability" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="SelfFunded" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.uspGetClientListByOwnerID" Method="uspGetClientListByOwnerID">
    <Parameter Name="OwnerID" Parameter="ownerID" Type="System.Guid" DbType="UniqueIdentifier" />
    <ElementType Name="uspGetClientListByOwnerIDResult">
      <Column Name="ClientID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="OwnerID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="EmployerName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="TaxID" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.uspGetClientPlanOptions" Method="uspGetClientPlanOptions">
    <Parameter Name="OwnerID" Parameter="ownerID" Type="System.Guid" DbType="UniqueIdentifier" />
    <ElementType Name="uspGetClientPlanOptionsResult">
      <Column Name="ClientPlanOptionID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="OwnerID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="PlanName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.uspGetEnrolleeByID" Method="uspGetEnrolleeByID">
    <Parameter Name="EnrolleeID" Parameter="enrolleeID" Type="System.Guid" DbType="UniqueIdentifier" />
    <ElementType Name="uspGetEnrolleeByIDResult">
      <Column Name="EnrolleeID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="OwnerID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="BirthDate" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SubmissionComplete" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AddedBy" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="AddedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.uspGetSubmissionsByClientID" Method="uspGetSubmissionsByClientID">
    <Parameter Name="ownerid" Type="System.Guid" DbType="UniqueIdentifier" />
    <ElementType Name="uspGetSubmissionsByClientIDResult">
      <Column Name="SubmissionID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="OwnerID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="FileName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Extension" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="AddedBy" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="AddedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.uspGetSubmissionsByClientIDBrokerView" Method="uspGetSubmissionsByClientIDBrokerView">
    <Parameter Name="ownerid" Type="System.Guid" DbType="UniqueIdentifier" />
    <ElementType Name="uspGetSubmissionsByClientIDBrokerViewResult">
      <Column Name="addeddate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="lastname" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="firstname" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="birthdate" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.uspInsertClient" Method="uspInsertClient">
    <Parameter Name="ClientID" Parameter="clientID" Type="System.Guid" DbType="UniqueIdentifier" />
    <Parameter Name="OwnerID" Parameter="ownerID" Type="System.Guid" DbType="UniqueIdentifier" />
    <Parameter Name="EmployerName" Parameter="employerName" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="TaxID" Parameter="taxID" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="EligableEmployees" Parameter="eligableEmployees" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.uspInsertClientCarrier" Method="uspInsertClientCarrier">
    <Parameter Name="CID" Parameter="cID" Type="System.Guid" DbType="UniqueIdentifier" />
    <Parameter Name="Client" Parameter="client" Type="System.Guid" DbType="UniqueIdentifier" />
    <Parameter Name="Carrier" Parameter="carrier" Type="System.String" DbType="VarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.uspInsertClientInfo" Method="uspInsertClientInfo">
    <Parameter Name="contactID" Type="System.Guid" DbType="UniqueIdentifier" />
    <Parameter Name="ownerID" Type="System.Guid" DbType="UniqueIdentifier" />
    <Parameter Name="phone" Type="System.String" DbType="Text" />
    <Parameter Name="fax" Type="System.String" DbType="Text" />
    <Parameter Name="address" Type="System.String" DbType="Text" />
    <Parameter Name="city" Type="System.String" DbType="Text" />
    <Parameter Name="state" Type="System.String" DbType="Text" />
    <Parameter Name="zip" Type="System.String" DbType="Text" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.uspInsertClientOptions" Method="uspInsertClientOptions">
    <Parameter Name="OptionsID" Parameter="optionsID" Type="System.Guid" DbType="UniqueIdentifier" />
    <Parameter Name="OwnerID" Parameter="ownerID" Type="System.Guid" DbType="UniqueIdentifier" />
    <Parameter Name="med" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="den" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="lif" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="vis" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="dis" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="sf" Type="System.Boolean" DbType="Bit" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.uspInsertEnrollee" Method="uspInsertEnrollee">
    <Parameter Name="EnrolleeID" Parameter="enrolleeID" Type="System.Guid" DbType="UniqueIdentifier" />
    <Parameter Name="OwnerID" Parameter="ownerID" Type="System.Guid" DbType="UniqueIdentifier" />
    <Parameter Name="FirstName" Parameter="firstName" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="LastName" Parameter="lastName" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="BirthDate" Parameter="birthDate" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="isComplete" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="AddedBy" Parameter="addedBy" Type="System.String" DbType="VarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
</Database>